global_costmap:
    global_frame: map
    robot_base_frame: base_link
    always_send_full_costmap: true
    width: 605
    height: 557
    origin_x: -4.605329
    origin_y: -2.250000
    resolution: 0.05
    update_frequency: 4.0
    #4.0
    #10.0
    # 20.0
    publish_frequency: 4.0
    # 10.0
    
    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

    static_layer:
        enabled:              true
        map_topic:            "/map"
    
    
    inflation_layer:
        enabled:              true
        cost_scaling_factor:  5  
        inflation_radius:     0.72
